### ISSUE TITLE
i cannot move

### ISSUE THREAD

**Issue by Moaseries** [demixitho3/Bugtracker_Oficcial#22]
i create goblin rogue and buy instant level 85.and do all quest in kezan and i ride ship from kezan to the lost isles due to quest change.and i got bug
![IMG20211001182806](https://user-images.githubusercontent.com/90981652/135616882-4ad97c80-a9d8-4bdf-b45b-da48b4d99c4a.jpg)
![IMG20211001182751](https://user-images.githubusercontent.com/90981652/135616920-66530588-90ce-4ebb-9b3c-84e54266f8fc.jpg)

**Comment by demixitho3** [comment]
I need the wow head link of the mission that leaves you frozen

**Comment by demixitho3** [comment]
https://es.wowhead.com/quest=14126/ahorros-de-toda-una-vida
a lo que realizas
esta mision te deja el debuf de muerte
y el npc no te libera
para seguir con la cadena
